CREATE TABLE Accounts (
    id INT PRIMARY KEY AUTO_INCREMENT,
    account_number CHAR(12) UNIQUE NOT NULL,
    user_id INT NOT NULL,
    balance DECIMAL(10,2) DEFAULT 0,
    account_type VARCHAR(50) NOT NULL,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,
    modified DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);